@BubberDinner.Api_HostAddress = http://localhost:5080

@host = http://localhost:5080


POST {{host}}/auth/register
Content-Type: application/json

{
  "firstname": "masood",
  "lastname": "asfdaf",
  "password": "234",
  "email": "fiajfda"
}



###
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "fiajfda",
  "password": "234"
}

